### ISSUE TITLE
Missing documentation and issues

### ISSUE THREAD

**Issue by SalahAdDin** [neon-jungle/wagtail-translations#5]
Hi, 

I'm trying implements this package for translations but i have a problem:

```
Migrations for 'home':
  home/migrations/0006_auto_20170406_0640.py:
    - Create model TranslationHomePage
    - Add field translatedpage_ptr to homepage
    - Alter field page_ptr on homepage
 salahaddin@TulipanROG  ~/Proyectos/uzman/uzman   internationalization ● ? ↑23  (uzman)  ./manage.py migrate                                                                                             ✓  5410  14:40:37 
Operations to perform:
  Apply all migrations: about, admin, auth, axes, blog, contenttypes, core, dashboard, flatpages, home, jet, marketing, person, robots, services, sessions, sites, standard, taggit, wagtail_embed_videos, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailmetadata, wagtailredirects, wagtailsearch, wagtailsearchpromotions, wagtailtranslations, wagtailusers, work
Running migrations:
  Applying home.0006_auto_20170406_0640...Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: no se permiten múltiples llaves primarias para la tabla «home_homepage»


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 84, in database_forwards
    field,
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/backends/postgresql/schema.py", line 21, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 409, in add_field
    self.execute(sql, params)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: no se permiten múltiples llaves primarias para la tabla «home_homepage»
```

How can i solve it?

There aren't here any documentation about it, so, is very hard for us solve this problem.

**Comment by SalahAdDin** [comment]
I have this problem yet.

**Comment by mx-moth** [comment]
Documentation is still to come, this is very much a work in progress. I am sorry it does not work for you yet. I will add documentation once the code has stopped changing.

**Comment by SalahAdDin** [comment]
When will you stop?
